POST http://localhost:3000/evaluate
Accept: application/json
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
Content-Length: 21

{"expression": "1+1"}

<> 2024-10-08T231014.201.html

###

POST http://localhost:3000/evaluate
Accept: application/json
Content-Length: 21
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip

{"expression": "1+1"}

<> 2024-10-08T230412.201.html

###

POST http://localhost:3000/evaluate
Accept: application/json
Content-Length: 21
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip

{"expression": "1+1"}

<> 2024-10-08T230357.201.html

###

POST http://localhost:3000/evaluate
Accept: application/json
Content-Length: 21
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip

{"expression": "1+1"}

<> 2024-10-08T225904.201.html

###

POST http://localhost:3000/evaluate
Accept: application/json
Content-Length: 21
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip

{"expression": "1+1"}

<> 2024-10-08T225603.201.html

###

POST http://localhost:3000/evaluate
Accept: application/json
Content-Length: 21
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip

{"expression": "1+1"}

<> 2024-10-08T225318.201.html

###

POST http://localhost:3000/evaluate
Accept: application/json
Content-Length: 21
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip

{"expression": "1+1"}

<> 2024-10-08T225252.201.html

###

POST http://localhost:3000/evaluate
Accept: application/json
Content-Length: 21
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip

{"expression": "1+1"}

<> 2024-10-08T224857.201.html

###

POST http://localhost:3000/evaluate
Accept: application/json
Content-Length: 21
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip

{"expression": "1+1"}

<> 2024-10-08T224838.201.html

###

POST http://localhost:3000/evaluate
Accept: application/json
Content-Length: 21
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip

{"expression": "1+1"}

<> 2024-10-08T224614.201.html

###

POST http://localhost:3000/evaluate
Accept: application/json
Content-Length: 21
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip

{"expression": "1+1"}

<> 2024-10-08T224403.500.json

###

POST http://localhost:3000/evaluate
Accept: application/json
Content-Length: 21
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip

{"expression": "1+1"}

<> 2024-10-08T224320.500.json

###

POST http://localhost:3000/evaluate
Accept: application/json
Content-Length: 21
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip

{"expression": "1+1"}

<> 2024-10-08T224030.500.json

###

POST http://localhost:3000/evaluate
Accept: application/json
Content-Length: 21
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip

{"expression": "1+1"}

<> 2024-10-08T223818.500.json

###

POST http://localhost:3000/evaluate
Accept: application/json
Content-Length: 21
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip

{"expression": "1+1"}

<> 2024-10-08T223744.500.json

###

GET http://localhost:3000/evaluate
Accept: application/json
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.1.1
Accept-Encoding: br, deflate, gzip, x-gzip
content-length: 21

{"expression": "1+1"}

<> 2024-10-08T223738.404.json

###

